title: "KLECHDY - Folklor i Legendy Polskie"
tagline: "OPOWIEŚCI Z POGRANICZA PRAWDY I LĘKU"
description: "Opowieści z pogranicza prawdy, baśni i lęku. Utkane z ludowych wierzeń, zapomnianych notatek etnografów i pożółkłych kart archiwów."
host: "Oskar Jaśniewski"
logo: "klechdy.png"
