title: Klechdy | Folklor i legendy polskie
tagline: FOLKLOR I LEGENDY POLSKIE
description: Opowieści z pogranicza prawdy, baśni i lęku. Utkane z ludowych
  wierzeń, zapomnianych notatek etnografów i pożółkłych kart archiwów.
host: Oskar Jaśniewski
logo: klechdy.png
